spring:
  application:
    name: driver-demo
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/driver}
    username: "postgres"
    password: "password"
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect